#!/bin/zsh

src=
opt=

out_file=./a.out

while [ "$1" != "" ] ; do
	if [ ${1:0:1} = "-" ] ; then
		opt="${opt}"\ "$1"
	else
		src="${src}"\ "$1"
	fi
	shift
done

# eval expand ${opt}
eval cc ${opt} -lm -xc -o ${out_file} <( cat << EOT
	#include <stdio.h>
	#include <stdlib.h>
	#include <math.h>

	typedef unsigned char  uchar;
	typedef unsigned short ushort;
	typedef unsigned int   uint;
	typedef unsigned long  ulong;

	int main(int argc, const char *argv[])
	{
		${src};
		return 0;
	}
EOT
) && ${out_file} && rm ${out_file}
