#!/bin/sh

if [ $# -lt 2 ] ; then echo "usage: rep str [str...] count" > /dev/stderr ; exit 1; fi

eval num=\${$#}

str=`echo "$*" | sed 's/ [^ ]*$/ /'`

for i in `seq ${num}`; do echo -n "${str}"; done; echo -e "\b"
