#!/usr/bin/awk -f

function disp(lvl, str,    i)
{
	if (lvl > level) {
		print str
		return
	}
	for (i = 1; i <= dat_num[lvl]; i++)
		disp(lvl + 1, str OFS dat[lvl, i])
}

BEGIN {
	OFS = (FS == " " ? "\t" : FS)
	#ORS = ""

	RS = ""
	FS = "\n"
}

{
	level++
	dat_num[level] = NF
	for (i = 1; i <= NF; i++)
		if ($i !~ ("^" ign))
			dat_num[level]--
		else
			dat[level, i] = $i
}

END {
	for (i = 1; i <= dat_num[1]; i++)
		disp(1 + 1, dat[1, i])
}
