#!/usr/bin/awk -f
BEGIN {
	if (ARGV[1] ~ /^-F/) {
		sub(/^-F/, "", ARGV[1])
		FS = ARGV[1]
		ARGV[1] = ""
	}

	OFS = (FS == " " ? "\t" : FS)
}

FNR == 1{
	for (i = 1; i <= NF; i++)
		col_title[i] = $i
	next
}

{
	for (i = 2; i <= NF; i++)
		print $1, col_title[i], $i
}
